### PR TITLE
Refactoring of the issue parser

### PR DESCRIPTION
**Pull request by karlcow**
- Simplifying some functions
- Making it more efficient, aka not parsing twice the same things
- gather ONLY the bugs related to firefox, mozilla.

### CODE REVIEW

**Comment by hallvors** [comment]
(I've on purpose left the "filter out non-Firefox bugs" stuff to the "customer" of this script - maybe not the most efficient way to do it but I thought it's better to have this as a more general purpose building block)

**Comment by hallvors** [comment]
Or that was the intention. Seems I checked in a change meant for the AWCY version here :-p

**Comment by karlcow** [comment]
I can change and grab everything, I did mozilla only because it's what you were implying in the comment for AWCY. :) As you wish both ways are fine with me.

**Comment by hallvors** [comment]
```
def get_webcompat_data(url_repo):
```

What AWCY actually does is "from extract_id_title_url import get_webcompat_data" so I'd prefer that function actually knowing (or defaulting to) what the actual webcompat repo URL is.. ;)

Secondly, we can perhaps sort out the moz/non-moz dilemma by adding a "filter_on_labels" argument?

```
def get_webcompat_data(filter_on_labels=[], url_repo=URL_REPO):
```

maybe?

**Comment by karlcow** [comment]
Yup. We can do this. No issue. 
I'll modify tomorrow if you want.

**Comment by karlcow** [comment]
@hallvors 

`filter_on_labels=[]` is more complicated. I mean not to implement, but to do it properly and in a way which makes sense. Let's rename it `browser_filter = ''`.

We define a `browser_labels_whitelist = ['firefox', 'chrome', 'safari', 'ie', …]` (later it will be easier because this list will be controlled by having the right namespace directly in the label name).
- browser_filter is empty, we grab everything. **Issue**: some bzlike keyword do not make sense.
- browser_filter = `firefox`, we grab only things related to firefox. No specific issue.

What are the data you want to gather and in which way?

**Comment by hallvors** [comment]
I can see use cases where you would like for example the bugs labelled 'firefox' and 'mobile'.. browser_filter='' sounds OK, though, the consumer of data can always do more filtering.

**Comment by karlcow** [comment]
If we want to versatile. We need to reorganize a bit differently.
Here we are packing every actions magically in one thing and then torturing the parameters. Not good and smelly. :pig_nose: 

I propose to reorganize a bit the code then, with more functions that you can import in another code. So instead of 

``` python
from extract_id_title_url import get_webcompat_data
```

We can specialize a bit with export for csv, for moz_bugzilla, etc.
`get_webcompat_data` would just fetch the data and create a dataset.
- `filter_bugs(dataset)` gives a sub dataset with the same format.
- `csv_format(dataset)`
- `bzlike_format(dataset)`

Would it be better?

``` python
from extract_id_title_url import get_webcompat_data
from extract_id_title_url import bzlike_format
```

**Comment by hallvors** [comment]
Sounds good

**Pull request merged**
